#!/usr/bin/env bash
# Bootstrap Firefly for the public demo stack and write demo/.env.demo.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
COMPOSE_FILE="$ROOT/demo/docker-compose.demo.yml"
ENV_FILE="$ROOT/demo/.env.demo"
TOKEN_NAME="${DEMO_TOKEN_NAME:-FF3 Lantern Demo}"
FIREFLY_SERVICE_EMAIL="${DEMO_FIREFLY_SERVICE_EMAIL:-lantern-service@ff3lantern.internal}"
FIREFLY_SERVICE_PASSWORD="${DEMO_FIREFLY_SERVICE_PASSWORD:-$(openssl rand -base64 24)}"
FIREFLY_DEMO_EMAIL="${DEMO_FIREFLY_EMAIL:-demo@demo.ts}"
FIREFLY_DEMO_PASSWORD="${DEMO_FIREFLY_PASSWORD:-password123}"

cd "$ROOT"

compose() {
  docker compose -f "$COMPOSE_FILE" "$@"
}

firefly_exec() {
  compose exec -T firefly "$@"
}

echo "==> Firefly migrations + Passport"
firefly_exec php artisan migrate --force
firefly_exec php artisan passport:keys --force
firefly_exec php artisan passport:client --personal --no-interaction --name="$TOKEN_NAME"

echo "==> Demo Firefly users (service PAT + browser demo login)"
compose cp "$ROOT/demo/seed/bootstrap-demo-firefly.php" "firefly:/tmp/bootstrap-demo-firefly.php"
TOKEN="$(
  firefly_exec php /tmp/bootstrap-demo-firefly.php \
    "$FIREFLY_SERVICE_EMAIL" "$FIREFLY_SERVICE_PASSWORD" \
    "$FIREFLY_DEMO_EMAIL" "$FIREFLY_DEMO_PASSWORD" \
    "$TOKEN_NAME" 2>/dev/null \
    | grep -Eo 'eyJ[A-Za-z0-9._-]+' \
    | tail -1 \
    | tr -d '\r\n'
)"

if [[ -z "$TOKEN" ]]; then
  echo "ERROR: failed to create Firefly personal access token" >&2
  exit 1
fi

host_port="${DEMO_FIREFLY_PORT:-8088}"
public_url="${FF3LANTERN_FIREFLY_PUBLIC_URL:-http://127.0.0.1:${host_port}}"
cors="${DEMO_CORS_ORIGINS:-http://127.0.0.1:8080,http://localhost:8080}"

cat >"$ENV_FILE" <<EOF
# Generated by demo/seed/bootstrap-demo.sh — gitignored
FIREFLY_API_TOKEN=$TOKEN
FIREFLY_BASE_URL=http://127.0.0.1:${host_port}
FF3LANTERN_FIREFLY_PUBLIC_URL=$public_url
CORS_ALLOWED_ORIGINS=$cors
EOF
chmod 600 "$ENV_FILE"
echo "==> Wrote $ENV_FILE"
